"""Add initial agency schema structure

Revision ID: 1987d3241f40
Revises:
Create Date: 2026-09-06 04:14:53.336255

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.dialects import postgresql

from quick_chat_api.migrations.utils import (
    create_optimistic_lock_trigger,
    drop_optimistic_lock_trigger,
)

# revision identifiers, used by Alembic.
revision: str = "1987d3241f40"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_record",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("case_number", sa.Text(), nullable=False),
        sa.Column("ticket_number", sa.Text(), nullable=True),
        sa.Column("ia_reference_number", sa.Text(), nullable=True),
        sa.Column("case_type", sa.Text(), nullable=False),
        sa.Column("incident_date", sa.Date(), nullable=True),
        sa.Column("incident_time", sa.Time(), nullable=True),
        sa.Column("incident_location", sa.Text(), nullable=True),
        sa.Column("issuer_name", sa.Text(), nullable=True),
        sa.Column("issuer_identifier", sa.Text(), nullable=True),
        sa.Column("hearing_date", sa.Date(), nullable=True),
        sa.Column("hearing_time", sa.Time(), nullable=True),
        sa.Column("case_status", sa.Text(), server_default="OPEN", nullable=False),
        sa.Column("is_case_closed", sa.Boolean(), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("issue_time", sa.Time(), nullable=True),
        sa.Column("case_subtype", sa.Text(), nullable=False),
        sa.Column("review_status", sa.Text(), server_default="CLERK", nullable=False),
        sa.Column("county_name", sa.Text(), nullable=True),
        sa.Column(
            "must_appear", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("legacy_case_status", sa.Text(), nullable=True),
        sa.Column("case_title", sa.Text(), nullable=True),
        sa.Column("additional_notes", sa.Text(), nullable=True),
        sa.Column("incident_number", sa.Text(), nullable=True),
        sa.Column("primary_internal_form_id", sa.UUID(), nullable=True),
        sa.Column("party_pretrial_plea", sa.Text(), nullable=True),
        sa.Column(
            "is_juvenile", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_felony", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("hearing_types", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    create_optimistic_lock_trigger(
        "case_record", context.get_context().version_table_schema
    )
    op.create_index(
        op.f("ix_case_record_case_status"), "case_record", ["case_status"], unique=False
    )
    op.create_index(
        op.f("ix_case_record_case_subtype"),
        "case_record",
        ["case_subtype"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_record_case_type"), "case_record", ["case_type"], unique=False
    )
    op.create_index(
        op.f("ix_case_record_created_on"), "case_record", ["created_on"], unique=False
    )
    op.create_index(
        op.f("ix_case_record_ticket_number"),
        "case_record",
        ["ticket_number"],
        unique=True,
    )
    op.create_table(
        "case_charge",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("case_record_id", sa.UUID(), nullable=False),
        sa.Column("charge_code", sa.Text(), nullable=False),
        sa.Column("charge_type", sa.Text(), nullable=True),
        sa.Column("charge_description", sa.Text(), nullable=False),
        sa.Column("is_charge_closed", sa.Boolean(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("court_only_fine", sa.Boolean(), nullable=False),
        sa.Column(
            "void", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_record.id"],
            name="case_charge_case_record_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    create_optimistic_lock_trigger(
        "case_charge", context.get_context().version_table_schema
    )
    op.create_index(
        op.f("ix_case_charge_case_record_id"),
        "case_charge",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_charge_created_on"), "case_charge", ["created_on"], unique=False
    )
    op.create_table(
        "criminal",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("case_record_id", sa.UUID(), nullable=False),
        sa.Column(
            "is_arrested", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("arrested_date", sa.Date(), nullable=True),
        sa.Column("arrested_time", sa.Time(), nullable=True),
        sa.Column("arrest_location", sa.Text(), nullable=True),
        sa.Column("warrant_type", sa.Text(), nullable=True),
        sa.Column(
            "is_warrant_issued",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("warrant_issued_date", sa.Date(), nullable=True),
        sa.Column("warrant_issued_time", sa.Time(), nullable=True),
        sa.Column("warrant_number", sa.Text(), nullable=True),
        sa.Column("observation_text", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"], ["case_record.id"], name="criminal_case_record_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    create_optimistic_lock_trigger(
        "criminal", context.get_context().version_table_schema
    )
    op.create_index(
        op.f("ix_criminal_case_record_id"), "criminal", ["case_record_id"], unique=True
    )
    op.create_index(
        op.f("ix_criminal_created_on"), "criminal", ["created_on"], unique=False
    )
    op.create_table(
        "party_detail",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("case_record_id", sa.UUID(), nullable=False),
        sa.Column("party_type", sa.Text(), nullable=False),
        sa.Column("ssn_id", sa.Text(), nullable=True),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("middle_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("suffix", sa.Text(), nullable=True),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column(
            "is_primary_party",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("race", sa.Text(), nullable=True),
        sa.Column("sex", sa.Text(), nullable=True),
        sa.Column("ethnicity", sa.Text(), nullable=True),
        sa.Column("eye_color", sa.Text(), nullable=True),
        sa.Column("hair_color", sa.Text(), nullable=True),
        sa.Column("height", sa.Text(), nullable=True),
        sa.Column("weight", sa.Text(), nullable=True),
        sa.Column("license_type", sa.Text(), nullable=True),
        sa.Column("license_number", sa.Text(), nullable=True),
        sa.Column("license_state_code", sa.Text(), nullable=True),
        sa.Column("phone_number", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("party_organization", sa.Text(), nullable=True),
        sa.Column(
            "is_license_suspended",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_license_surrendered",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_commercial_license",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_juvenile", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("internal_form_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_record.id"],
            name="party_detail_case_record_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id", "case_record_id", name="uq_party_detail_id_case_record"
        ),
    )
    create_optimistic_lock_trigger(
        "party_detail", context.get_context().version_table_schema
    )
    op.create_index(
        "idx_first_name_trgm",
        "party_detail",
        ["first_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"first_name": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_full_name_trgm",
        "party_detail",
        ["full_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"full_name": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_last_name_trgm",
        "party_detail",
        ["last_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"last_name": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_party_detail_case_record_id"),
        "party_detail",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_party_detail_created_on"), "party_detail", ["created_on"], unique=False
    )
    op.create_index(
        op.f("ix_party_detail_internal_form_id"),
        "party_detail",
        ["internal_form_id"],
        unique=False,
    )
    op.create_table(
        "payment_record",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("case_record_id", sa.UUID(), nullable=True),
        sa.Column("payee_name", sa.Text(), nullable=True),
        sa.Column("payee_address", sa.Text(), nullable=True),
        sa.Column("payee_email", sa.Text(), nullable=True),
        sa.Column("service_fee", sa.DECIMAL(precision=8, scale=2), nullable=False),
        sa.Column("payment_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("amount", sa.DECIMAL(precision=8, scale=2), nullable=False),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column("card_last_4", sa.Text(), nullable=True),
        sa.Column("card_brand", sa.Text(), nullable=True),
        sa.Column("card_type", sa.Text(), nullable=True),
        sa.Column("exp_year", sa.Text(), nullable=True),
        sa.Column("exp_month", sa.Text(), nullable=True),
        sa.Column("payment_method", sa.Text(), nullable=True),
        sa.Column("payment_mode", sa.Text(), nullable=True),
        sa.Column("receipt_number", sa.Text(), nullable=True),
        sa.Column("consider_as_full", sa.Boolean(), nullable=False),
        sa.Column("consider_as_full_reason", sa.Text(), nullable=True),
        sa.Column(
            "payment_window", sa.Text(), server_default="CMS_WFE", nullable=False
        ),
        sa.Column("public_reference_id", sa.Text(), nullable=True),
        sa.Column("reference_number", sa.Text(), nullable=True),
        sa.Column("qp_payment_id", sa.Text(), nullable=True),
        sa.Column(
            "void", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("void_reason", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_record.id"],
            name="payment_record_case_record_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    create_optimistic_lock_trigger(
        "payment_record", context.get_context().version_table_schema
    )
    op.create_index(
        op.f("ix_payment_record_case_record_id"),
        "payment_record",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_record_created_on"),
        "payment_record",
        ["created_on"],
        unique=False,
    )
    op.create_table(
        "vehicle_detail",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("case_record_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_make", sa.Text(), nullable=True),
        sa.Column("vehicle_model", sa.Text(), nullable=True),
        sa.Column("vehicle_year", sa.Text(), nullable=True),
        sa.Column("legal_speed_rate", sa.Text(), nullable=True),
        sa.Column("recorded_speed_rate", sa.Text(), nullable=True),
        sa.Column("vehicle_plate", sa.Text(), nullable=True),
        sa.Column("vehicle_color", sa.Text(), nullable=True),
        sa.Column("plate_expiration_year", sa.Text(), nullable=True),
        sa.Column("vehicle_type", sa.Text(), nullable=True),
        sa.Column("vehicle_state_code", sa.Text(), nullable=True),
        sa.Column(
            "is_commercial_vehicle",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("vehicle_vin", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_record.id"],
            name="vehicle_details_case_record_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    create_optimistic_lock_trigger(
        "vehicle_detail", context.get_context().version_table_schema
    )
    op.create_index(
        op.f("ix_vehicle_detail_case_record_id"),
        "vehicle_detail",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vehicle_detail_created_on"),
        "vehicle_detail",
        ["created_on"],
        unique=False,
    )
    op.create_table(
        "address_detail",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("party_detail_id", sa.UUID(), nullable=False),
        sa.Column("case_record_id", sa.UUID(), nullable=False),
        sa.Column("address_line_1", sa.Text(), nullable=True),
        sa.Column("address_line_2", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("zip_code", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("address_type", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_record.id"],
            name="fk_address_detail_case_record_id",
        ),
        sa.ForeignKeyConstraint(
            ["party_detail_id"],
            ["party_detail.id"],
            name="address_detail_party_detail_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    create_optimistic_lock_trigger(
        "address_detail", context.get_context().version_table_schema
    )
    op.create_index(
        op.f("ix_address_detail_case_record_id"),
        "address_detail",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_address_detail_created_on"),
        "address_detail",
        ["created_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_address_detail_party_detail_id"),
        "address_detail",
        ["party_detail_id"],
        unique=False,
    )
    op.create_index(
        "uq_default_address_per_party",
        "address_detail",
        ["party_detail_id"],
        unique=True,
        postgresql_where=sa.text("is_default = true AND is_active = true"),
    )
    op.create_table(
        "case_appearance",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("case_record_id", sa.UUID(), nullable=False),
        sa.Column("hearing_types", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("hearing_result", sa.Text(), nullable=True),
        sa.Column("hearing_notes", sa.Text(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("check_in_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legal_representative_id", sa.UUID(), nullable=True),
        sa.Column("translator_language", sa.Text(), nullable=True),
        sa.Column("fta_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_case_appearance_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_record.id"],
            name="case_appearance_case_record_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["legal_representative_id"],
            ["party_detail.id"],
            name="case_appearance_legal_representative_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["next_case_appearance_id"],
            ["case_appearance.id"],
            name="case_appearance_next_case_appearance_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    create_optimistic_lock_trigger(
        "case_appearance", context.get_context().version_table_schema
    )
    op.create_index(
        "idx_case_record_id", "case_appearance", ["case_record_id"], unique=False
    )
    op.create_index(
        op.f("ix_case_appearance_case_record_id"),
        "case_appearance",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_appearance_created_on"),
        "case_appearance",
        ["created_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_appearance_legal_representative_id"),
        "case_appearance",
        ["legal_representative_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_appearance_next_case_appearance_id"),
        "case_appearance",
        ["next_case_appearance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_appearance_status"), "case_appearance", ["status"], unique=False
    )
    op.create_table(
        "imposed_disposition",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("case_charge_id", sa.UUID(), nullable=True),
        sa.Column("case_record_id", sa.UUID(), nullable=False),
        sa.Column("disposition_type", sa.Text(), nullable=True),
        sa.Column("finding", sa.Text(), nullable=True),
        sa.Column("disposed_on", sa.Date(), nullable=True),
        sa.Column(
            "is_conclusive",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_charge_id"],
            ["case_charge.id"],
            name="imposed_disposition_case_charge_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_record.id"],
            name="imposed_disposition_case_record_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    create_optimistic_lock_trigger(
        "imposed_disposition", context.get_context().version_table_schema
    )
    op.create_index(
        op.f("ix_imposed_disposition_case_charge_id"),
        "imposed_disposition",
        ["case_charge_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_imposed_disposition_case_record_id"),
        "imposed_disposition",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_imposed_disposition_created_on"),
        "imposed_disposition",
        ["created_on"],
        unique=False,
    )
    op.create_index(
        "uq_imposed_disposition_case_charge",
        "imposed_disposition",
        ["case_record_id", "case_charge_id"],
        unique=True,
        postgresql_where=sa.text("case_charge_id IS NOT NULL"),
    )
    op.create_table(
        "imposed_sanction",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("case_record_id", sa.UUID(), nullable=False),
        sa.Column("case_charge_id", sa.UUID(), nullable=True),
        sa.Column("sanction_type", sa.Text(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "mark_as_completed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_conclusive",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "sanction_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_charge_id"],
            ["case_charge.id"],
            name="imposed_sanction_case_charge_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"],
            ["case_record.id"],
            name="imposed_sanction_case_record_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    create_optimistic_lock_trigger(
        "imposed_sanction", context.get_context().version_table_schema
    )
    op.create_index(
        op.f("ix_imposed_sanction_case_charge_id"),
        "imposed_sanction",
        ["case_charge_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_imposed_sanction_case_record_id"),
        "imposed_sanction",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_imposed_sanction_created_on"),
        "imposed_sanction",
        ["created_on"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_imposed_sanction_created_on"), table_name="imposed_sanction")
    op.drop_index(
        op.f("ix_imposed_sanction_case_record_id"), table_name="imposed_sanction"
    )
    op.drop_index(
        op.f("ix_imposed_sanction_case_charge_id"), table_name="imposed_sanction"
    )
    drop_optimistic_lock_trigger(
        "imposed_sanction", context.get_context().version_table_schema
    )
    op.drop_table("imposed_sanction")
    op.drop_index(
        "uq_imposed_disposition_case_charge",
        table_name="imposed_disposition",
        postgresql_where=sa.text("case_charge_id IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_imposed_disposition_created_on"), table_name="imposed_disposition"
    )
    op.drop_index(
        op.f("ix_imposed_disposition_case_record_id"), table_name="imposed_disposition"
    )
    op.drop_index(
        op.f("ix_imposed_disposition_case_charge_id"), table_name="imposed_disposition"
    )
    drop_optimistic_lock_trigger(
        "imposed_disposition", context.get_context().version_table_schema
    )
    op.drop_table("imposed_disposition")
    op.drop_index(op.f("ix_case_appearance_status"), table_name="case_appearance")
    op.drop_index(
        op.f("ix_case_appearance_next_case_appearance_id"), table_name="case_appearance"
    )
    op.drop_index(
        op.f("ix_case_appearance_legal_representative_id"), table_name="case_appearance"
    )
    op.drop_index(op.f("ix_case_appearance_created_on"), table_name="case_appearance")
    op.drop_index(
        op.f("ix_case_appearance_case_record_id"), table_name="case_appearance"
    )
    op.drop_index("idx_case_record_id", table_name="case_appearance")
    drop_optimistic_lock_trigger(
        "case_appearance", context.get_context().version_table_schema
    )
    op.drop_table("case_appearance")
    op.drop_index(
        "uq_default_address_per_party",
        table_name="address_detail",
        postgresql_where=sa.text("is_default = true AND is_active = true"),
    )
    op.drop_index(
        op.f("ix_address_detail_party_detail_id"), table_name="address_detail"
    )
    op.drop_index(op.f("ix_address_detail_created_on"), table_name="address_detail")
    op.drop_index(op.f("ix_address_detail_case_record_id"), table_name="address_detail")
    drop_optimistic_lock_trigger(
        "address_detail", context.get_context().version_table_schema
    )
    op.drop_table("address_detail")
    op.drop_index(op.f("ix_vehicle_detail_created_on"), table_name="vehicle_detail")
    op.drop_index(op.f("ix_vehicle_detail_case_record_id"), table_name="vehicle_detail")
    drop_optimistic_lock_trigger(
        "vehicle_detail", context.get_context().version_table_schema
    )
    op.drop_table("vehicle_detail")
    op.drop_index(op.f("ix_payment_record_created_on"), table_name="payment_record")
    op.drop_index(op.f("ix_payment_record_case_record_id"), table_name="payment_record")
    drop_optimistic_lock_trigger(
        "payment_record", context.get_context().version_table_schema
    )
    op.drop_table("payment_record")
    op.drop_index(op.f("ix_party_detail_internal_form_id"), table_name="party_detail")
    op.drop_index(op.f("ix_party_detail_created_on"), table_name="party_detail")
    op.drop_index(op.f("ix_party_detail_case_record_id"), table_name="party_detail")
    op.drop_index(
        "idx_last_name_trgm",
        table_name="party_detail",
        postgresql_using="gin",
        postgresql_ops={"last_name": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_full_name_trgm",
        table_name="party_detail",
        postgresql_using="gin",
        postgresql_ops={"full_name": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_first_name_trgm",
        table_name="party_detail",
        postgresql_using="gin",
        postgresql_ops={"first_name": "gin_trgm_ops"},
    )
    drop_optimistic_lock_trigger(
        "party_detail", context.get_context().version_table_schema
    )
    op.drop_table("party_detail")
    op.drop_index(op.f("ix_criminal_created_on"), table_name="criminal")
    op.drop_index(op.f("ix_criminal_case_record_id"), table_name="criminal")
    drop_optimistic_lock_trigger("criminal", context.get_context().version_table_schema)
    op.drop_table("criminal")
    op.drop_index(op.f("ix_case_charge_created_on"), table_name="case_charge")
    op.drop_index(op.f("ix_case_charge_case_record_id"), table_name="case_charge")
    drop_optimistic_lock_trigger(
        "case_charge", context.get_context().version_table_schema
    )
    op.drop_table("case_charge")
    op.drop_index(op.f("ix_case_record_ticket_number"), table_name="case_record")
    op.drop_index(op.f("ix_case_record_created_on"), table_name="case_record")
    op.drop_index(op.f("ix_case_record_case_type"), table_name="case_record")
    op.drop_index(op.f("ix_case_record_case_subtype"), table_name="case_record")
    op.drop_index(op.f("ix_case_record_case_status"), table_name="case_record")
    drop_optimistic_lock_trigger(
        "case_record", context.get_context().version_table_schema
    )
    op.drop_table("case_record")
    # ### end Alembic commands ###
