"""Add initial vector embedding table structure

Revision ID: 9e9d5258d192
Revises: 1987d3241f40
Create Date: 2026-09-06 04:17:01.648657

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import context, op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from quick_chat_api.migrations.utils import (
    create_optimistic_lock_trigger,
    drop_optimistic_lock_trigger,
)

# revision identifiers, used by Alembic.
revision: str = "9e9d5258d192"
down_revision: str | None = "1987d3241f40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvectorscale provides the diskann index access method used below.
    # CASCADE also creates the base `vector` extension it depends on.
    # Extensions are database-wide, so IF NOT EXISTS keeps this idempotent
    # across the per-agency-schema migration runs.
    op.execute("CREATE EXTENSION IF NOT EXISTS vectorscale CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_knowledge_source",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("case_record_id", sa.UUID(), nullable=True),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("source_table", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Text(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("storage_uri", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.Column(
            "source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"], ["case_record.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_table",
            "source_id",
            "source_type",
            name="uq_ai_knowledge_source_origin",
        ),
    )
    create_optimistic_lock_trigger(
        "ai_knowledge_source", context.get_context().version_table_schema
    )
    op.create_index(
        "ix_ai_knowledge_source_case_id",
        "ai_knowledge_source",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_knowledge_source_case_record_id"),
        "ai_knowledge_source",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_knowledge_source_created_on"),
        "ai_knowledge_source",
        ["created_on"],
        unique=False,
    )
    op.create_index(
        "ix_ai_knowledge_source_metadata_gin",
        "ai_knowledge_source",
        ["source_metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_ai_knowledge_source_source_type"),
        "ai_knowledge_source",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_knowledge_source_status"),
        "ai_knowledge_source",
        ["status"],
        unique=False,
    )
    op.create_table(
        "ai_knowledge_chunk",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("case_record_id", sa.UUID(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("embedding", Vector(768), nullable=False),
        sa.Column("embedding_model", sa.Text(), nullable=False),
        sa.Column("embedding_version", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["case_record_id"], ["case_record.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["ai_knowledge_source.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "chunk_index", name="uq_ai_knowledge_chunk_doc_idx"
        ),
    )
    create_optimistic_lock_trigger(
        "ai_knowledge_chunk", context.get_context().version_table_schema
    )
    op.create_index(
        "ix_ai_knowledge_chunk_case_id",
        "ai_knowledge_chunk",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_knowledge_chunk_case_record_id"),
        "ai_knowledge_chunk",
        ["case_record_id"],
        unique=False,
    )
    op.create_index(
        "ix_ai_knowledge_chunk_content_hash",
        "ai_knowledge_chunk",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_knowledge_chunk_created_on"),
        "ai_knowledge_chunk",
        ["created_on"],
        unique=False,
    )
    op.create_index(
        "ix_ai_knowledge_chunk_embedding_diskann",
        "ai_knowledge_chunk",
        ["embedding"],
        unique=False,
        postgresql_using="diskann",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_ai_knowledge_chunk_embedding_diskann", table_name="ai_knowledge_chunk"
    )
    op.drop_index(
        op.f("ix_ai_knowledge_chunk_created_on"), table_name="ai_knowledge_chunk"
    )
    op.drop_index("ix_ai_knowledge_chunk_content_hash", table_name="ai_knowledge_chunk")
    op.drop_index(
        op.f("ix_ai_knowledge_chunk_case_record_id"), table_name="ai_knowledge_chunk"
    )
    op.drop_index("ix_ai_knowledge_chunk_case_id", table_name="ai_knowledge_chunk")
    drop_optimistic_lock_trigger(
        "ai_knowledge_chunk", context.get_context().version_table_schema
    )
    op.drop_table("ai_knowledge_chunk")
    op.drop_index(
        op.f("ix_ai_knowledge_source_status"), table_name="ai_knowledge_source"
    )
    op.drop_index(
        op.f("ix_ai_knowledge_source_source_type"), table_name="ai_knowledge_source"
    )
    op.drop_index(
        "ix_ai_knowledge_source_metadata_gin",
        table_name="ai_knowledge_source",
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_ai_knowledge_source_created_on"), table_name="ai_knowledge_source"
    )
    op.drop_index(
        op.f("ix_ai_knowledge_source_case_record_id"), table_name="ai_knowledge_source"
    )
    op.drop_index("ix_ai_knowledge_source_case_id", table_name="ai_knowledge_source")
    drop_optimistic_lock_trigger(
        "ai_knowledge_source", context.get_context().version_table_schema
    )
    op.drop_table("ai_knowledge_source")
    # ### end Alembic commands ###
