from enum import Enum


class CaseTypes(str, Enum):
    CIVIL = "CIVIL"
    CRIMINAL = "CRIMINAL"
    PETITION = "PETITION"
    GLOBAL = "GLOBAL"


class ChargeType(str, Enum):
    CRIMINAL = "CRIMINAL"
    TRAFFIC = "TRAFFIC"
    CIVIL_TRAFFIC = "CIVIL_TRAFFIC"


class LicenseType(str, Enum):
    COMMERCIAL_DRIVER_LICENSE = "COMMERCIAL_DRIVER_LICENSE"
    COMMERCIAL_MOTOR_VEHICLE = "COMMERCIAL_MOTOR_VEHICLE"
    HAZARDOUS_MATERIALS = "HAZARDOUS_MATERIALS"
    NUCLEAR = "NUCLEAR"


class WarrantType(str, Enum):
    ARREST = "ARREST"
    BENCH = "BENCH"


class PaymentStatus(str, Enum):
    NO_PAYMENT_DUE = "NO_PAYMENT_DUE"
    UNPAID = "UNPAID"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PAID = "PAID"


class CaseStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    DISPOSED = "DISPOSED"
    REOPENED = "REOPENED"
    INACTIVE = "INACTIVE"
    ADJUDICATED = "ADJUDICATED"


class AddressType(str, Enum):
    HOME = "HOME"
    OFFICE = "OFFICE"
    MAILING = "MAILING"
    ALTERNATE = "ALTERNATE"
    OTHER = "OTHER"


class PartyType(str, Enum):
    LIENHOLDER = "LIENHOLDER"
    TRANSLATOR = "TRANSLATOR"
    ATTORNEY = "ATTORNEY"
    CITIZEN = "CITIZEN"
    DEFENDANT = "DEFENDANT"
    INTERESTED_PARTY = "INTERESTED_PARTY"
    JUDGE = "JUDGE"
    CLERK = "CLERK"
    PROSECUTOR = "PROSECUTOR"
    VICTIM = "VICTIM"
    WITNESS = "WITNESS"
    LEGAL_REPRESENTATIVE = "LEGAL_REPRESENTATIVE"
    PLAINTIFF = "PLAINTIFF"
    CO_PLAINTIFF = "CO_PLAINTIFF"
    OFFICER = "OFFICER"
    RESPONDENT = "RESPONDENT"
    OTHER_PROTECTED_PARTY = "OTHER_PROTECTED_PARTY"
    CHILD = "CHILD"
    RELATIVE = "RELATIVE"
    CIVIL_DEFENDANT = "CIVIL_DEFENDANT"
    JUVENILE_OTHER_PARTY = "JUVENILE_OTHER_PARTY"
    CIVIL_OTHER_PARTY = "CIVIL_OTHER_PARTY"
    CIVIL_SUBJECT = "CIVIL_SUBJECT"
    PETITIONER = "PETITIONER"
    CO_PETITIONER = "CO_PETITIONER"


class Race(str, Enum):
    WHITE = "WHITE"
    BLACK_OR_AFRICAN_AMERICAN = "BLACK_OR_AFRICAN_AMERICAN"
    AMERICAN_INDIAN_OR_ALASKA_NATIVE = "AMERICAN_INDIAN_OR_ALASKA_NATIVE"
    HISPANIC_OR_LATINO = "HISPANIC_OR_LATINO"
    ASIAN = "ASIAN"
    NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER = (
        "NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER"
    )
    UNKNOWN = "UNKNOWN"
    INDIAN = "INDIAN"
    NATIVE_AMERICAN = "NATIVE_AMERICAN"
    HISPANIC = "HISPANIC"
    CAUCASIAN = "CAUCASIAN"
    OTHER = "OTHER"
    MULTI_RACIAL = "MULTI_RACIAL"


class Sex(str, Enum):
    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class Ethnicity(str, Enum):
    ASIAN = "ASIAN"
    BLACK = "BLACK"
    WHITE = "WHITE"
    HISPANIC = "HISPANIC"
    MIDDLE_EASTERN = "MIDDLE_EASTERN"
    NATIVE_AMERICAN = "NATIVE_AMERICAN"
    PACIFIC_ISLANDER = "PACIFIC_ISLANDER"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"
    NOT_HISPANIC_OR_LATINO = "NOT_HISPANIC_OR_LATINO"
    ARAPAHO = "ARAPAHO"
    JICARILLA_APACHE = "JICARILLA_APACHE"
    ANGLO_SAXON = "ANGLO_SAXON"
    UTE_MOUNTAIN_UTE = "UTE_MOUNTAIN_UTE"
    NAVAJO = "NAVAJO"
    SOUTHERN_UTE = "SOUTHERN_UTE"
    NORTHERN_UTE = "NORTHERN_UTE"


class EyeColor(str, Enum):
    BLACK = "BLACK"
    BLUE = "BLUE"
    BROWN = "BROWN"
    GRAY = "GRAY"
    GREEN = "GREEN"
    HAZEL = "HAZEL"
    MAROON = "MAROON"
    PINK = "PINK"
    MULTI_COLORED = "MULTI_COLORED"
    UNKNOWN = "UNKNOWN"


class HairColor(str, Enum):
    BALD = "BALD"
    BLACK = "BLACK"
    BLONDE = "BLONDE"
    BROWN = "BROWN"
    GRAY = "GRAY"
    RED = "RED"
    SANDY = "SANDY"
    WHITE = "WHITE"
    UNKNOWN = "UNKNOWN"
    BLUE = "BLUE"
    GREEN = "GREEN"
    ORANGE = "ORANGE"
    PURPLE = "PURPLE"
    PINK = "PINK"


class Suffix(str, Enum):
    MR = "MR"
    MRS = "MRS"
    MS = "MS"
    MISS = "MISS"
    DR = "DR"
    PROF = "PROF"
    REV = "REV"


class ReviewStatus(str, Enum):
    CLERK = "CLERK"
    JUDGE = "JUDGE"


class CaseAppearanceStatus(str, Enum):
    UNREGISTERED = "UNREGISTERED"
    REGISTERED = "REGISTERED"
    FTA = "FTA"
    ADJUDICATED = "ADJUDICATED"


class AIKnowledgeSourceType(str, Enum):
    """Indexed entity kinds; also the projector registry keys and the vector payload `source_type`."""

    CASE = "case"
    CASE_SUMMARY = "case_summary"
    PARTY = "party"
    CHARGE = "charge"
    APPEARANCE = "appearance"
    PAYMENT = "payment"
    DISPOSITION = "disposition"
    SANCTION = "sanction"
    CRIMINAL = "criminal"
    VEHICLE = "vehicle"
    ADDRESS = "address"


_T = AIKnowledgeSourceType
# Domain groupings for `retrieve(source_types=...)`; every source type belongs to exactly one.
SOURCE_TYPE_GROUPS: dict[str, list[str]] = {
    "financial": [_T.PAYMENT.value],
    "outcome": [_T.CHARGE.value, _T.DISPOSITION.value, _T.SANCTION.value],
    "people": [_T.PARTY.value, _T.ADDRESS.value],
    "hearings": [_T.APPEARANCE.value],
    "case_level": [
        _T.CASE.value,
        _T.CASE_SUMMARY.value,
        _T.CRIMINAL.value,
        _T.VEHICLE.value,
    ],
}


class Domain(str, Enum):
    CASE = "case"
    HEARINGS = "hearings"
    FINANCIAL = "financial"


# Agent/structured-query domains (S1.10); distinct from SOURCE_TYPE_GROUPS, which only filters retrieval.
SOURCE_TYPE_DOMAIN: dict[AIKnowledgeSourceType, Domain] = {
    _T.CASE: Domain.CASE,
    _T.CASE_SUMMARY: Domain.CASE,
    _T.PARTY: Domain.CASE,
    _T.CHARGE: Domain.CASE,
    _T.APPEARANCE: Domain.HEARINGS,
    _T.PAYMENT: Domain.FINANCIAL,
    _T.DISPOSITION: Domain.FINANCIAL,
    _T.SANCTION: Domain.FINANCIAL,
    # ponytail: criminal/vehicle/address unmapped until an S4 agent owns them
}


class HearingType(str, Enum):
    ARRAIGNMENT = "ARRAIGNMENT"
    AOP = "AOP"
    MOTION_HEARING = "MOTION_HEARING"
    PRE_TRIAL = "PRE_TRIAL"
    PERSONAL_HEARING = "PERSONAL_HEARING"
    RESTITUTION = "RESTITUTION"
    REVIEW_HEARING = "REVIEW_HEARING"
    RELEASE = "RELEASE"
    REVOCATION = "REVOCATION"
    SHOW = "SHOW"
    TRIAL = "TRIAL"
    CASE_REVIEW = "CASE_REVIEW"
    STATUS = "STATUS"
    SENTENCING = "SENTENCING"

    BOND_FORFEITURE_REVOCATION = "BOND_FORFEITURE_REVOCATION"
    MOTION_REVOCATION = "MOTION_REVOCATION"
    REVIEW = "REVIEW"
    FURTHER_PROCEEDINGS = "FURTHER_PROCEEDINGS"
    WELLNESS_COURT_REVIEW = "WELLNESS_COURT_REVIEW"
    READINESS = "READINESS"
    TRIAL_TO_THE_COURT = "TRIAL_TO_THE_COURT"
    MOTION = "MOTION"
    ORDER_TO_SHOW_CAUSE = "ORDER_TO_SHOW_CAUSE"
    RESTITUTION_HEARING = "RESTITUTION_HEARING"
    JURY_TRIAL = "JURY_TRIAL"
    HEARING = "HEARING"
    PAPER_REVIEW = "PAPER_REVIEW"
    SUPPRESSION = "SUPPRESSION"
    BENCH_WARRANT_RETURN = "BENCH_WARRANT_RETURN"
    EXTRADITION_ADVISEMENT = "EXTRADITION_ADVISEMENT"
    EXTRADITION_HEARING = "EXTRADITION_HEARING"
    TRAFFIC = "TRAFFIC"
    FAMILY_TREATMENT_COURT = "FAMILY_TREATMENT_COURT"
    ADMINISTRATIVE = "ADMINISTRATIVE"
