"""Add inital config schema structure

Revision ID: e7acfa4231a3
Revises:
Create Date: 2026-09-06 00:54:11.529880

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

from quick_chat_api.migrations.utils import (
    create_optimistic_lock_trigger,
    drop_optimistic_lock_trigger,
)

# revision identifiers, used by Alembic.
revision: str = "e7acfa4231a3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS config")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # Create check modification_version trigger
    op.execute("""
    CREATE OR REPLACE FUNCTION check_version_no()
    RETURNS trigger AS $$
    BEGIN
        IF NEW.modification_version IS DISTINCT FROM OLD.modification_version THEN
            RAISE EXCEPTION USING
                MESSAGE = format(
                    'Row was modified. Expected version=%s, actual=%s',
                    OLD.modification_version,
                    NEW.modification_version
                ),
                ERRCODE = '40001';
        END IF;

        NEW.modification_version = OLD.modification_version + 1;
        NEW.modified_on = now();

        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE OR REPLACE FUNCTION event_notify_trigger()
    RETURNS trigger AS $$
    BEGIN
        RAISE NOTICE 'Trigger fired for channel=% and event_type=%', NEW.event_channel, NEW.event_type;

        PERFORM pg_notify(
            NEW.event_channel,
            json_build_object(
                'event', TG_OP,
                'event_type', NEW.event_type,
                'description', NEW.description
            )::text
        );
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.create_table(
        "agencies",
        sa.Column("agency_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("abbr", sa.String(), nullable=False),
        sa.Column("app_name", sa.String(), nullable=False),
        sa.Column("profile_logo_s3_key", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column(
            "unique_reference_id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("agency_id"),
        sa.UniqueConstraint("abbr"),
        sa.UniqueConstraint("app_name"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("unique_reference_id"),
        schema="config",
    )
    create_optimistic_lock_trigger("agencies", "config")
    op.create_index(
        op.f("ix_config_agencies_created_on"),
        "agencies",
        ["created_on"],
        unique=False,
        schema="config",
    )
    op.create_table(
        "config",
        sa.Column("config_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agency_name", sa.String(), nullable=True),
        sa.Column("config_section", sa.String(), nullable=True),
        sa.Column("config_key", sa.String(), nullable=True),
        sa.Column("config_value", sa.JSON(), nullable=True),
        sa.Column("config_description", sa.Text(), nullable=True),
        sa.Column("exposable", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column(
            "unique_reference_id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("config_id"),
        sa.UniqueConstraint("unique_reference_id"),
        schema="config",
    )
    create_optimistic_lock_trigger("config", "config")
    op.create_index(
        op.f("ix_config_config_created_on"),
        "config",
        ["created_on"],
        unique=False,
        schema="config",
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cognito_id", sa.Text(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column(
            "is_super_admin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_by", sa.String(length=64), nullable=True),
        sa.Column(
            "modification_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column(
            "unique_reference_id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("cognito_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("unique_reference_id"),
        schema="config",
    )
    create_optimistic_lock_trigger("user", "config")
    op.create_index(
        op.f("ix_config_user_created_on"),
        "user",
        ["created_on"],
        unique=False,
        schema="config",
    )

    op.execute(
        text("""
            INSERT INTO config.agencies 
            (name, abbr, app_name, code, is_active, created_on, created_by, modified_on, modified_by, modification_version) 
            VALUES 
            ('southern_ute', 'SUT', 'Southern Ute', '123', true, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system', 1)
            ON CONFLICT (name) DO NOTHING;
            """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_config_user_created_on"), table_name="user", schema="config")
    drop_optimistic_lock_trigger("user", "config")
    op.drop_table("user", schema="config")
    op.drop_index(
        op.f("ix_config_config_created_on"), table_name="config", schema="config"
    )
    drop_optimistic_lock_trigger("config", "config")
    op.drop_table("config", schema="config")
    op.drop_index(
        op.f("ix_config_agencies_created_on"), table_name="agencies", schema="config"
    )
    drop_optimistic_lock_trigger("agencies", "config")
    op.drop_table("agencies", schema="config")

    op.execute("DROP SCHEMA IF EXISTS config CASCADE;")
    # ### end Alembic commands ###
